In [2]:
from sodapy import Socrata
import pandas as pd

client = Socrata("data.cityofchicago.org", None)
results = client.get("r5kz-chrr", limit=10)
df = pd.DataFrame.from_records(results)
df.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,id,license_id,account_number,site_number,legal_name,doing_business_as_name,address,city,state,zip_code,...,license_status,latitude,longitude,location,:@computed_region_vrxf_vc4k,:@computed_region_awaf_s7ux,:@computed_region_6mkv_f3dw,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu,ssa
0,3090925-20260701,3090925,426697,2,CARLOS CASTRO,CAMILA'S ANTIQUES RESALE,5616 W IRVING PARK RD,CHICAGO,IL,60634,...,AAI,41.9532825241,-87.7676946866,"{'latitude': '41.9532825240786', 'longitude': ...",15,25,22254,26,19,NaN
1,2718748-20260716,3084477,354572,4,THE TOY BUSINESS LLC,play,5311 N CLARK ST,CHICAGO,IL,60640,...,AAI,41.978402769,-87.6681870245,"{'latitude': '41.97840276903265', 'longitude':...",76,40,22616,540,16,22
2,2622006-20260716,3084208,293117,2,AMERICAN ACCORD FOOD CORP,AMERICAN ACCORD FOOD CORP,10543-45 S EWING AVE,CHICAGO,IL,60617,...,AAI,41.7032801506,-87.53513858,"{'latitude': '41.70328015056708', 'longitude':...",49,47,21202,715,47,NaN
3,2807984-20260116,3059595,478380,1,DHAN CARES LLC,THE GODDARD SCHOOL OF WEST LOOP,776 W QUINCY ST 1,CHICAGO,IL,60661,...,AAI,41.8786924799,-87.6471440061,"{'latitude': '41.87869247985044', 'longitude':...",29,41,4452,786,46,16
4,2846350-20260716,3085442,485788,1,YI LI FOOD BOX INC.,YI LI FOOD BOX INC.,4310 S SHIELDS AVE 2ND,CHICAGO,IL,60609,...,AAI,41.815978537,-87.6348530304,"{'latitude': '41.81597853695627', 'longitude':...",3,12,14924,189,9,13

In [4]:
df.columns.tolist()

['id',
 'license_id',
 'account_number',
 'site_number',
 'legal_name',
 'doing_business_as_name',
 'address',
 'city',
 'state',
 'zip_code',
 'ward',
 'precinct',
 'ward_precinct',
 'police_district',
 'community_area',
 'community_area_name',
 'neighborhood',
 'license_code',
 'license_description',
 'business_activity_id',
 'business_activity',
 'license_number',
 'application_type',
 'application_created_date',
 'application_requirements_complete',
 'payment_date',
 'conditional_approval',
 'license_start_date',
 'expiration_date',
 'license_approved_for_issuance',
 'date_issued',
 'license_status',
 'latitude',
 'longitude',
 'location',
 ':@computed_region_vrxf_vc4k',
 ':@computed_region_awaf_s7ux',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_43wa_7qmu',
 'ssa']

In [5]:
df['application_type'].unique()

<StringArray>
['ISSUE', 'RENEW']
Length: 2, dtype: str

In [10]:
from sodapy import Socrata
import pandas as pd

import sys
sys.path.append('..')

from config import SOCRATA_TOKEN

client = Socrata("data.cityofchicago.org", SOCRATA_TOKEN)

In [11]:
import os
print(os.getcwd())

/Users/minjookim/Documents/library-business-did/src

In [12]:
library_results = client.get("x8fc-8rcq", limit=100)
libraries_df = pd.DataFrame.from_records(library_results)
libraries_df.head()

,branch_,service_hours,address,city,state,zip,phone,website,branch_email,location,:@computed_region_rpca_8um6,:@computed_region_vrxf_vc4k,:@computed_region_6mkv_f3dw,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu
0,Albany Park,"Mon. & Wed., 10-6; Tues. & Thurs., Noon-8; Fri...",3401 W. Foster Ave.,Chicago,IL,60625,(773) 539-5450,{'url': 'https://www.chipublib.org/locations/3/'},albanypark@chipublib.org,"{'latitude': '41.97557881655979', 'longitude':...",20,13,21849,167,38
1,Altgeld,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",955 E. 131st St.,Chicago,IL,60827,(312) 747-3270,{'url': 'https://www.chipublib.org/locations/4/'},altgeld@chipublib.org,"{'latitude': '41.65719847558056', 'longitude':...",47,51,4460,10,43
2,Archer Heights,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",5055 S. Archer Ave.,Chicago,IL,60632,(312) 747-9241,{'url': 'https://www.chipublib.org/locations/5/'},archerheights@chipublib.org,"{'latitude': '41.80110836194246', 'longitude':...",56,54,22248,697,8
3,Austin,"Mon. & Wed., Noon-8; Tues. & Thurs., 10-6; Fri...",5615 W. Race Ave.,Chicago,IL,60644,(312) 746-5038,{'url': 'https://www.chipublib.org/locations/6/'},austin@chipublib.org,"{'latitude': '41.88917312206642', 'longitude':...",32,26,22216,672,7
4,Austin-Irving,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",6100 W. Irving Park Rd.,Chicago,IL,60634,(312) 744-6222,{'url': 'https://www.chipublib.org/locations/7/'},austin-irving@chipublib.org,"{'latitude': '41.95312267684315', 'longitude':...",52,15,22254,131,19

In [14]:
libraries_df.columns.tolist()

['branch_',
 'service_hours',
 'address',
 'city',
 'state',
 'zip',
 'phone',
 'website',
 'branch_email',
 'location',
 ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_43wa_7qmu']

In [15]:
libraries_df['location'].iloc[0]

{'latitude': '41.97557881655979',
 'longitude': '-87.71361314512697',
 'human_address': '{"address": "", "city": "", "state": "", "zip": ""}'}

In [17]:
libraries_df['lib_lat'] = libraries_df['location'].apply(lambda x: float(x['latitude']))
libraries_df['lib_long'] = libraries_df['location'].apply(lambda x: float(x['longitude']))

libraries_df[['branch_', 'address', 'lib_lat', 'lib_long']].head()

          branch_                  address    lib_lat   lib_long
0     Albany Park      3401 W. Foster Ave.  41.975579 -87.713613
1         Altgeld         955 E. 131st St.  41.657198 -87.598838
2  Archer Heights      5055 S. Archer Ave.  41.801108 -87.726484
3          Austin        5615 W. Race Ave.  41.889173 -87.765820
4   Austin-Irving  6100 W. Irving Park Rd.  41.953123 -87.779285

In [22]:
print(len(libraries_df))
libraries_df.to_csv('../data/raw/cpl_libraries_raw.csv', index=False)

81